unique_ids:
  assets:
    standard-page.html: MZP6FRFANS5B5MUS32EPVWOFUMZE3COU
    theme.css: FXUN3QV6LBCL52JPQJ5CTWZCKJMPQG2R
  forms:
    Form1: JW6X7NQ6FQYRVSYYWQXK4PU7KIF2FJLO
  modules: {}
  scripts: {}
  server_modules: {}
